//xây dựng server image
FROM gcc:7.4.0
MAINTAINER  vuongnguyen
RUN mkdir -p /home/my-app
WORKDIR /home/my-app
COPY . /home/my-app
EXPOSE 8888
RUN gcc server.c -o server -pthread ; gcc client.c -o client

//tạo image
sudo docker build -t gcc-image:lastest .

//client ở host connect tới server ở container
sudo docker run -it --name=gcc-server --net="host" gcc-image:lastest // create và start



sudo docker start <container-name> // startcontainer có sẵn
sudo docker attach <container-name> //truy cập lại foreground lần nữa



sudo docker rm <my_container> //xóa container

sudo docker container ls -all //list ra tất cả container 

sudo docker ps -q | xargs sudo docker kill //list ra các container đang chạy rồi kill

//create data container 
docker create -v /data --name dataContainer 
docker cp server.c client.c dataContainer:/data/

//tham chiếu dataContainer
docker run --volumes-from dataContainer gcc-server-image --name gcc-server-container ls /data

//export and import dataContainer
docker export dataContainer > dataContainer.tar
docker import dataContainer.tar